# Generated by Django 6.0.4 on 2026-05-03 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(choices=[('perth', 'Perth'), ('brisbane', 'Brisbane'), ('melbourne', 'Melbourne')], max_length=100)),
                ('type', models.CharField(choices=[('paid', 'Paid'), ('volunteer', 'Volunteer')], max_length=20)),
                ('budget', models.CharField(choices=[('under_500', 'Under $500'), ('over_500', 'Over $500')], max_length=20)),
                ('timeline', models.CharField(choices=[('1_2_weeks', '1-2 weeks'), ('3_4_weeks', '3-4 weeks'), ('1_3_months', '1-3 months')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Just an idea'), ('mvp', 'MVP'), ('launched', 'Launched')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industries', models.ManyToManyField(blank=True, to='devs.industry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('skills_needed', models.ManyToManyField(blank=True, to='devs.skill')),
            ],
        ),
    ]
